"""
Signal 5A — FEVER dataset semantic search (local cache).

Loads precomputed embeddings from data/fever_cache/ at startup and performs
fast cosine similarity search in-process using numpy.

Cache files expected (generated by the preprocessing notebook):
  - data/fever_cache/fever_embeddings.npy   (shape: [N, 384], float32)
  - data/fever_cache/fever_claims.pkl       (list[str], length N)
  - data/fever_cache/fever_labels.pkl       (list[str], length N, values: SUPPORTS/REFUTES/NOT ENOUGH INFO)

On Railway (or any deploy without local cache files), set:
  DISABLE_FEVER_INDEX=true
or simply leave the cache files absent — the signal degrades gracefully
to a neutral score of 50 without crashing.

Scoring:
  cosine >= 0.85 + SUPPORTS  → 90–95
  cosine >= 0.85 + REFUTES   → 5–15
  no match / NOT ENOUGH INFO → 50 (neutral)
"""

import os
import pickle
import logging
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)

# ── Cache paths ────────────────────────────────────────────────────────────
_BACKEND_DIR   = Path(__file__).parent.parent
_CACHE_DIR     = _BACKEND_DIR / "data" / "fever_cache"
_EMBEDDINGS_PATH = _CACHE_DIR / "fever_embeddings.npy"
_CLAIMS_PATH     = _CACHE_DIR / "fever_claims.pkl"
_LABELS_PATH     = _CACHE_DIR / "fever_labels.pkl"

# ── In-memory index ────────────────────────────────────────────────────────
_embeddings: np.ndarray | None = None   # shape (N, 384), float32, L2-normalised
_claims: list[str] | None = None
_labels: list[str] | None = None

# ── Sentence-transformer encoder (lazy-loaded on first query) ──────────────
_encoder_model = None


def _get_encoder():
    global _encoder_model
    if _encoder_model is None:
        logger.info("[FEVER] Loading sentence-transformers encoder (all-MiniLM-L6-v2)…")
        from sentence_transformers import SentenceTransformer
        _encoder_model = SentenceTransformer("all-MiniLM-L6-v2")
        logger.info("[FEVER] Encoder ready.")
    return _encoder_model


# ── Disabled flag ─────────────────────────────────────────────────────────
# Set DISABLE_FEVER_INDEX=true in Railway env to skip loading cache entirely.
_FEVER_DISABLED = os.getenv("DISABLE_FEVER_INDEX", "").lower() in ("1", "true", "yes")


# ── Public API ─────────────────────────────────────────────────────────────

def load_fever_index():
    """
    Load the precomputed FEVER embeddings + metadata from local disk into RAM.
    Called once at startup from main.py.
    Safe no-op when cache files are absent (e.g. Railway deploy).
    """
    global _embeddings, _claims, _labels

    if _FEVER_DISABLED:
        logger.info("[FEVER] DISABLE_FEVER_INDEX=true — skipping local index load. Signal will return neutral score=50.")
        return

    missing = [p for p in (_EMBEDDINGS_PATH, _CLAIMS_PATH, _LABELS_PATH) if not p.exists()]
    if missing:
        logger.warning(
            "[FEVER] Cache files not found (expected in data/fever_cache/). "
            "FEVER signal disabled — all queries will return neutral score=50. "
            f"Missing: {[str(p.name) for p in missing]}"
        )
        return

    logger.info("[FEVER] Loading local FEVER cache from disk…")
    try:
        _embeddings = np.load(str(_EMBEDDINGS_PATH))       # (N, 384)
        with open(str(_CLAIMS_PATH), "rb") as f:
            _claims = pickle.load(f)
        with open(str(_LABELS_PATH), "rb") as f:
            _labels = pickle.load(f)

        logger.info(
            f"[FEVER] Index loaded: {_embeddings.shape[0]:,} claims "
            f"({_embeddings.nbytes / 1e6:.1f} MB)"
        )
    except Exception as e:
        logger.error(f"[FEVER] Failed to load cache: {e}. FEVER signal disabled.")
        _embeddings = _claims = _labels = None


def search_fever(query: str, top_k: int = 5) -> list[dict]:
    """
    Find the top-k most similar claims in the local FEVER index via cosine similarity.
    Returns empty list (gracefully) when index is not loaded.

    Returns:
        list of dicts with keys: claim, label, similarity
    """
    if _FEVER_DISABLED or _embeddings is None or _claims is None or _labels is None:
        return []

    if not query.strip():
        return []

    try:
        encoder = _get_encoder()
        query_vec = encoder.encode(
            [query],
            convert_to_numpy=True,
            normalize_embeddings=True,
        )[0].astype(np.float32)          # shape (384,)

        # Cosine similarity = dot product (both vectors already L2-normalised)
        sims = _embeddings @ query_vec   # shape (N,)

        top_indices = np.argpartition(sims, -top_k)[-top_k:]
        top_indices = top_indices[np.argsort(sims[top_indices])[::-1]]

        results = [
            {
                "claim":      _claims[i],
                "label":      _labels[i],
                "similarity": float(sims[i]),
            }
            for i in top_indices
        ]

        if results:
            logger.debug(
                f"[FEVER] top similarity={results[0]['similarity']:.4f} "
                f"| label={results[0]['label']}"
            )

        return results

    except Exception as e:
        logger.error(f"[FEVER] search_fever() error: {e}")
        return []


def compute_fever_score(claim: str) -> dict:
    """
    Compute the FEVER sub-signal score for a given claim.

    Returns:
        dict with keys: score, top_match, matches
    """
    # If the index is not loaded (e.g. Railway deploy), return neutral — no data to judge.
    if _FEVER_DISABLED or _embeddings is None:
        logger.info("[FEVER] Index not available — returning neutral score=50")
        return {"score": 50, "top_match": None, "matches": []}

    try:
        matches = search_fever(claim, top_k=3)
    except Exception as e:
        logger.error(f"[FEVER] compute_fever_score() error: {e}")
        return {"score": 50, "top_match": None, "matches": [], "error": str(e)}

    if not matches:
        # Index IS loaded but claim doesn't exist in any fact-checked dataset — suspicious.
        logger.info("[FEVER] No matches found in index — returning score=10")
        return {"score": 10, "top_match": None, "matches": []}

    top = matches[0]
    sim   = top["similarity"]
    label = top["label"]

    logger.info(
        f"[FEVER] query='{claim[:80]}' | "
        f"top_match='{top['claim'][:60]}' | "
        f"label={label} | similarity={sim:.4f}"
    )

    # ── Scoring logic ──────────────────────────────────────────────────────
    if sim >= 0.85:
        if label == "SUPPORTS":
            score = min(95, round(90 + (sim - 0.85) * 33))
        elif label == "REFUTES":
            score = max(5, round(15 - (sim - 0.85) * 67))
        else:
            # NOT ENOUGH INFO at high similarity
            if sim >= 0.95:
                score = 65
            elif sim >= 0.90:
                score = 60
            else:
                score = 55

    elif sim >= 0.70:
        if label == "SUPPORTS":
            score = round(60 + (sim - 0.70) * 200)   # 60–90
        elif label == "REFUTES":
            score = round(40 - (sim - 0.70) * 167)   # 40–15
        else:
            score = 50

    else:
        score = 10

    logger.info(f"[FEVER] final score={score} | sim={sim:.4f} | label={label}")

    return {
        "score": max(0, min(100, score)),
        "top_match": {
            "claim":      top["claim"],
            "label":      top["label"],
            "similarity": round(sim, 4),
        },
        "matches": [
            {
                "claim":      m["claim"],
                "label":      m["label"],
                "similarity": round(m["similarity"], 4),
            }
            for m in matches
        ],
    }
